---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:
    
    - name: Install Terraform
      ansible.builtin.command:
        cmd:  microdnf install -y yum-utils
      delegate_to: localhost



