---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform
 

  tasks:

    - name: List bucket content
      aws_s3:
        bucket: terraformfile9088
        object: "/terraform"
        dest: sbin
        mode: get

    - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
      ansible.builtin.shell: |
        terraform version
      register: hostname_output
      
    - name: show hostname
      debug:
        var: hostname_output.stdout_lines
