---
- name: Infrastructure Deployment
  hosts: localhost
  collections:chdir 
   - cloud.terraform


  tasks:
    
    - name: Install Terraform
      ansible.builtin.command:
        chdir: /usr/bin
        cmd:  ls -lrt
      delegate_to: localhost
      register: hostname_output

     
    - name: show hostname
      debug:
        var: hostname_output.stdout_lines   

        


