---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:
    
    - name: Simple GET operation
      amazon.aws.s3_object:
        bucket: terraformfile9088
        object: /terraform
        dest: /usr/bin/terraform
        mode: get

    - name: Basic deploy of n instance
      cloud.terraform.terraform:
       project_path: "environment/nonp/development/"
       state: present
       force_init: true
        


