---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:
    
    - name: Simple GET operation
      amazon.aws.s3_object:
        bucket: terraformfile9088
        object: /terraform
        dest: /usr/bin/terraform
        mode: get


