---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:
    
    - name: Install Terraform
      ansible.builtin.command:
        cmd:  microdnf install -y yum-utils
        cmd:  yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        cmd:  sudo yum -y install terraform
      delegate_to: localhost

    - name: checking Terraform
      ansible.builtin.command:
        cmd: terraform -help
      delegate_to: localhost
      register: hostname_output

    - name: show hostname
      debug:
        var: hostname_output.stdout_lines         


