---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:

    - name: List bucket content
      aws_s3:
        bucket: terraformfile9088
        object: "/terraform"
        dest: /sbin
        mode: get

    - name: Basic deploy of n instance
      cloud.terraform.terraform:
       project_path: "environment/nonp/development/"
       state: present
       force_init: true

