---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:
    
    - name: Install Terraform
      ansible.builtin.command:
        cmd:  microdnf install terraform-1.6.6-1.x86_64
        creates: /usr/bin/terraform
      delegate_to: localhost

    - name: Basic deploy of n instance
      cloud.terraform.terraform:
       project_path: "environment/nonp/development/"
       state: present
       force_init: true


