---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:
    
    - name: Install Terraform
      ansible.builtin.command:
        cmd:  microdnf install yum-utils
      delegate_to: localhost

    - name: checking Terraform
      ansible.builtin.command:
        cmd: terraform -help
      delegate_to: localhost
      register: hostname_output

    - name: show hostname
      debug:
        var: hostname_output.stdout_lines         


