---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform
 

  tasks:

   - name: Simple PUT operation
     ansible.builtin.shell: |
       cd /usr/local/sbin
       ls
     register: hostname_output

   - name: show hostname
     debug:
       var: hostname_output.stdout_lines
       
