---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform




  vars:
   location:
     development: "environment/nonp/development/"  
     test: "environment/nonp/test/"
 

  tasks:

   - name: Basic deploy of an instance
     cloud.terraform.terraform:
      project_path: "{{ location[development] }}"
      state: present
      force_init: true

   - name: Remove Instance
     cloud.terraform.terraform:
      project_path: "{{ location[development] }}"
      state: absent
      force_init: true
     tags:
       - never
       - remove

   - name: Wait to Completely Provision Instances
     pause:
       minutes: 2

   - name: Refresh Inventory
     meta: refresh_inventory

