---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:

    - name: Get dev file
      amazon.aws.s3_object:
        bucket: terraformfile9088
        object: terraform
        dest: usr/bin/terraform
        mode: get
      delegate_to: localhost
      register: hostname_outputew
        
    - name: show hostname
      debug:
        var: hostname_outputew.stdout_lines

    - name: installing Terraform
      ansible.builtin.command:
        cmd: terraform -help
      delegate_to: localhost
      register: hostname_outputewdf

    - name: show hostname
      debug:
        var: hostname_outputewdf.stdout_lines         
