---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:

    - name: installing Terraform
      ansible.builtin.command:
        cmd: dnf repolist
      delegate_to: localhost
      register: hostname_outputewdf

    - name: show hostname
      debug:
        var: hostname_outputewdf.stdout_lines   
        
        



        
