---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform


  tasks:

    - name: installing Terraform
      ansible.builtin.command:
        argv:
          - microdnf install yum-utils
          - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          - microdnf install terraform-1.6.6-1.x86_64
          - terraform -help
      delegate_to: localhost
      register: hostname_outputewdf

       
    - name: show hostname
      debug:  
        var: hostname_outputewdf.stdout_lines          
        



        
