resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

 
   hostname: ${module.dev-instances.instancehostname}
   instanceid: ${module.dev-instances.instanceid}
   public_ip: ${module.dev-instances.publicip}
   private_ip: ${module.dev-instances.private_ip}
   public_dns: ${module.dev-instances.public_dns}

    DOC
  filename = "../playbooks/ascs-infra-setup/group_vars/var2"
}
